"""
AR aging, DSO, and collections-priority scoring on the synthetic
order-to-cash dataset generated by 01_generate_synthetic_data.py.

Outputs:
  data/aging_summary.csv
  data/dso_trend.csv
  data/collections_priority_worklist.csv
  figures/aging_buckets.png
  figures/dso_trend.png
  figures/top_priority_accounts.png
"""
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

matplotlib.use("Agg")

HERE = Path(__file__).resolve().parent
PROJECT_DIR = HERE.parent
DATA_DIR = PROJECT_DIR / "data"
FIG_DIR = PROJECT_DIR / "figures"

AS_OF = pd.Timestamp("2026-06-30")

# --- palette (validated default categorical/sequential palette) ---
INK_PRIMARY = "#0b0b0b"
INK_SECONDARY = "#52514e"
INK_MUTED = "#898781"
GRID = "#e1e0d9"
SURFACE = "#fcfcfb"
BLUE = "#2a78d6"
SEQ_BLUE = ["#cde2fb", "#9ec5f4", "#5598e7", "#2a78d6", "#184f95"]  # light->dark, 5 steps
STATUS_GOOD = "#0ca30c"
STATUS_WARN = "#fab219"
STATUS_SERIOUS = "#ec835a"
STATUS_CRIT = "#d03b3b"

plt.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Segoe UI", "Arial", "sans-serif"],
    "axes.edgecolor": GRID,
    "axes.labelcolor": INK_SECONDARY,
    "text.color": INK_PRIMARY,
    "xtick.color": INK_MUTED,
    "ytick.color": INK_MUTED,
    "figure.facecolor": SURFACE,
    "axes.facecolor": SURFACE,
    "savefig.facecolor": SURFACE,
})


def load():
    customers = pd.read_csv(DATA_DIR / "customers.csv")
    invoices = pd.read_csv(DATA_DIR / "invoices.csv", parse_dates=["issue_date", "due_date", "payment_date"])
    return customers, invoices


def compute_aging(invoices: pd.DataFrame) -> pd.DataFrame:
    open_inv = invoices[invoices["status"] == "Open"].copy()
    open_inv["days_past_due"] = (AS_OF - open_inv["due_date"]).dt.days

    bins = [-10_000, 0, 30, 60, 90, 10_000]
    labels = ["Current", "1-30 Days", "31-60 Days", "61-90 Days", "90+ Days"]
    open_inv["aging_bucket"] = pd.cut(open_inv["days_past_due"], bins=bins, labels=labels)

    summary = open_inv.groupby("aging_bucket", observed=True)["amount"].agg(["sum", "count"]).reindex(labels)
    summary.columns = ["total_amount", "invoice_count"]
    summary = summary.fillna(0)
    return open_inv, summary


def compute_dso_trend(invoices: pd.DataFrame) -> pd.DataFrame:
    months = pd.date_range("2024-10-01", "2026-06-01", freq="MS")
    rows = []
    for month_start in months:
        month_end = month_start + pd.offsets.MonthEnd(0)
        # AR outstanding at month end: invoices issued by month_end, not yet paid by month_end (or paid after)
        issued = invoices[invoices["issue_date"] <= month_end]
        outstanding = issued[(issued["payment_date"].isna()) | (issued["payment_date"] > month_end)]
        outstanding = outstanding[outstanding["status"] != "Written Off"]
        ar_balance = outstanding["amount"].sum()

        # trailing-90-day average daily sales as of month_end
        window_start = month_end - pd.Timedelta(days=90)
        trailing_sales = invoices[(invoices["issue_date"] > window_start) & (invoices["issue_date"] <= month_end)]["amount"].sum()
        avg_daily_sales = trailing_sales / 90 if trailing_sales > 0 else np.nan

        dso = ar_balance / avg_daily_sales if avg_daily_sales else np.nan
        rows.append({"month": month_start.strftime("%Y-%m"), "ar_balance": ar_balance, "dso": dso})
    return pd.DataFrame(rows)


def compute_priority_worklist(customers: pd.DataFrame, open_inv: pd.DataFrame, all_invoices: pd.DataFrame) -> pd.DataFrame:
    # historical lateness: for each customer's PAID invoices, average days late vs. due date
    paid = all_invoices[all_invoices["status"] == "Paid"].copy()
    paid["days_late"] = (paid["payment_date"] - paid["due_date"]).dt.days
    hist = paid.groupby("customer_id")["days_late"].mean().rename("avg_days_late_hist")

    dispute_rate = (
        all_invoices.assign(is_bad=all_invoices["status"].isin(["Disputed", "Written Off"]))
        .groupby("customer_id")["is_bad"].mean().rename("dispute_writeoff_rate")
    )

    acct = open_inv.groupby("customer_id").agg(
        open_amount=("amount", "sum"),
        open_invoices=("amount", "count"),
        max_days_past_due=("days_past_due", "max"),
    ).reset_index()

    acct = acct.merge(customers, on="customer_id", how="left")
    acct = acct.merge(hist, on="customer_id", how="left")
    acct = acct.merge(dispute_rate, on="customer_id", how="left")
    acct["avg_days_late_hist"] = acct["avg_days_late_hist"].fillna(0).clip(lower=0)
    acct["dispute_writeoff_rate"] = acct["dispute_writeoff_rate"].fillna(0)

    # normalize components 0-1 and combine into a single priority score.
    def norm(s):
        rng = s.max() - s.min()
        return (s - s.min()) / rng if rng > 0 else s * 0

    acct["score_amount"] = norm(acct["open_amount"])
    acct["score_days_past_due"] = norm(acct["max_days_past_due"].clip(lower=0))
    acct["score_history"] = norm(acct["avg_days_late_hist"])
    acct["score_dispute_risk"] = norm(acct["dispute_writeoff_rate"])

    # weights: dollar exposure and lateness matter most; history/dispute risk as tiebreakers
    acct["priority_score"] = (
        0.40 * acct["score_amount"]
        + 0.35 * acct["score_days_past_due"]
        + 0.15 * acct["score_history"]
        + 0.10 * acct["score_dispute_risk"]
    ).round(3)

    acct = acct.sort_values("priority_score", ascending=False).reset_index(drop=True)
    acct.insert(0, "priority_rank", acct.index + 1)

    cols = [
        "priority_rank", "customer_id", "customer_name", "segment", "region",
        "open_amount", "open_invoices", "max_days_past_due",
        "avg_days_late_hist", "dispute_writeoff_rate", "priority_score",
    ]
    return acct[cols]


def make_figures(aging_summary: pd.DataFrame, dso_trend: pd.DataFrame, worklist: pd.DataFrame):
    FIG_DIR.mkdir(parents=True, exist_ok=True)

    # --- Aging buckets ---
    fig, ax = plt.subplots(figsize=(7, 4.2))
    x = np.arange(len(aging_summary))
    bars = ax.bar(x, aging_summary["total_amount"], color=SEQ_BLUE, width=0.62)
    ax.set_xticks(x)
    ax.set_xticklabels(aging_summary.index, fontsize=9)
    ax.set_ylabel("Open AR ($)")
    ax.set_title("Open AR by Aging Bucket", fontsize=12, color=INK_PRIMARY, loc="left", pad=12)
    ax.spines[["top", "right", "left"]].set_visible(False)
    ax.yaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    ax.tick_params(left=False)
    for rect, val in zip(bars, aging_summary["total_amount"]):
        ax.annotate(f"${val:,.0f}", (rect.get_x() + rect.get_width() / 2, rect.get_height()),
                    ha="center", va="bottom", fontsize=8.5, color=INK_SECONDARY, xytext=(0, 3), textcoords="offset points")
    fig.tight_layout()
    fig.savefig(FIG_DIR / "aging_buckets.png", dpi=160)
    plt.close(fig)

    # --- DSO trend ---
    fig, ax = plt.subplots(figsize=(8, 4.2))
    ax.plot(dso_trend["month"], dso_trend["dso"], color=BLUE, linewidth=2)
    ax.scatter([dso_trend["month"].iloc[-1]], [dso_trend["dso"].iloc[-1]], color=BLUE, s=28, zorder=3)
    ax.annotate(f"{dso_trend['dso'].iloc[-1]:.0f} days", (dso_trend["month"].iloc[-1], dso_trend["dso"].iloc[-1]),
                textcoords="offset points", xytext=(-8, 10), ha="right", fontsize=9, color=INK_PRIMARY, fontweight="bold")
    ax.set_ylabel("DSO (days)")
    ax.set_title("Days Sales Outstanding — Trailing 90-Day Basis", fontsize=12, color=INK_PRIMARY, loc="left", pad=12)
    ax.spines[["top", "right", "left"]].set_visible(False)
    ax.yaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    ax.tick_params(left=False, axis="x", rotation=45)
    step = max(1, len(dso_trend) // 12)
    ax.set_xticks(range(0, len(dso_trend), step))
    ax.set_xticklabels(dso_trend["month"].iloc[::step], fontsize=8)
    fig.tight_layout()
    fig.savefig(FIG_DIR / "dso_trend.png", dpi=160)
    plt.close(fig)

    # --- Top priority accounts ---
    top20 = worklist.head(20).iloc[::-1]
    fig, ax = plt.subplots(figsize=(8, 7))
    ax.barh(top20["customer_name"], top20["priority_score"], color=BLUE, height=0.62)
    ax.set_xlabel("Priority Score (0-1)")
    ax.set_title("Top 20 Accounts — Collections Priority", fontsize=12, color=INK_PRIMARY, loc="left", pad=12)
    ax.spines[["top", "right", "left"]].set_visible(False)
    ax.xaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    ax.tick_params(left=False, labelsize=8.5)
    fig.tight_layout()
    fig.savefig(FIG_DIR / "top_priority_accounts.png", dpi=160)
    plt.close(fig)


def main():
    customers, invoices = load()
    open_inv, aging_summary = compute_aging(invoices)
    dso_trend = compute_dso_trend(invoices)
    worklist = compute_priority_worklist(customers, open_inv, invoices)

    aging_summary.to_csv(DATA_DIR / "aging_summary.csv")
    dso_trend.to_csv(DATA_DIR / "dso_trend.csv", index=False)
    worklist.to_csv(DATA_DIR / "collections_priority_worklist.csv", index=False)

    make_figures(aging_summary, dso_trend, worklist)

    print("Aging summary:\n", aging_summary)
    print(f"\nLatest DSO: {dso_trend['dso'].iloc[-1]:.1f} days")
    print(f"\nTop 5 priority accounts:\n{worklist.head(5)[['priority_rank', 'customer_name', 'open_amount', 'priority_score']]}")


if __name__ == "__main__":
    main()
